import numpy as np

def calculate_population_metrics(file_path):
    # Load the results. Your script saves both a .npy and .npz file.
    # We'll use the .npz here since it's commonly used for multiple arrays.
    data = np.load(file_path)
    sr_mat = data['sr_mat'] if 'sr_mat' in data else data
    
    num_agents = sr_mat.shape[0]
    
    # 1. Calculate Self-SR (Mean of the diagonal line)
    # np.diagonal extracts the diagonal, np.nanmean ignores any NaN values
    self_sr_array = np.diagonal(sr_mat)
    self_sr = np.nanmean(self_sr_array)
    
    # 2. Calculate Cross-SR (Mean of everything excluding the diagonal)
    # np.eye creates a boolean mask of the diagonal. 
    # The bitwise NOT operator (~) inverts it to mask the off-diagonals.
    off_diagonal_mask = ~np.eye(num_agents, dtype=bool)
    cross_sr_array = sr_mat[off_diagonal_mask]
    cross_sr = np.nanmean(cross_sr_array)
    
    return self_sr, cross_sr

if __name__ == "__main__":
    # Replace this path with the actual path generated by your script's `save_root`
    # Example path based on your script's default arguments:
    path = "../../logs/vary_n_pop/torch_100net/sr_batched/fc_ppo_100net_invisible/grid5_img3_ni2_nw4_ms30_comm_field5/seed1/mode_test/normal/sr_eval.npz"
    
    try:
        self_sr, cross_sr = calculate_population_metrics(path)
        print("--- Population Evaluation Results ---")
        print(f"Self-SR:  {self_sr:.4f}")
        print(f"Cross-SR: {cross_sr:.4f}")
    except FileNotFoundError:
        print(f"Could not find the file at: {path}")
        print("Please double-check the path against your script's save_outputs directory.")