_wandb:
    value:
        cli_version: 0.18.7
        code_path: code/train_marl_ppo.py
        m: []
        python_version: 3.8.19
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 35
                - 55
            "4": 3.8.19
            "5": 0.18.7
            "8":
                - 5
            "12": 0.18.7
            "13": darwin-arm64
anneal_lr:
    value: true
batch_size:
    value: 1024
capture_video:
    value: false
clip_coef:
    value: 0.1
clip_vloss:
    value: true
cuda:
    value: true
ent_coef:
    value: 0.01
env_id:
    value: Foraging-Single-v1
exp_name:
    value: train_marl_ppo
gae_lambda:
    value: 0.95
gamma:
    value: 0.99
learning_rate:
    value: 0.00025
max_grad_norm:
    value: 0.5
minibatch_size:
    value: 256
norm_adv:
    value: true
num_envs:
    value: 8
num_iterations:
    value: 9765
num_minibatches:
    value: 4
num_steps:
    value: 128
seed:
    value: 1
target_kl:
    value: null
torch_deterministic:
    value: true
total_timesteps:
    value: 10000000
track:
    value: true
update_epochs:
    value: 4
vf_coef:
    value: 0.5
wandb_entity:
    value: maytusp
wandb_project_name:
    value: IPPO MA Foraging Game
